#!/usr/bin/env bash

unameOutput="$(uname -o)"
echo "${unameOutput}"

if [ "${unameOutput}" == "Cygwin" ]; then
    nohup cygstart index.html
elif [ "${unameOutput}" == "Linux" ]; then
    nohup xdg-open index.html
fi
rm nohup.out

